### ISSUE TITLE
What is streq and where do i get it?

### ISSUE THREAD

**Issue by The-Gmann** [B4nduty/bsdfwmi-1.21#2]
The title says it all.

**Comment by B4nduty** [comment]
StrEq is a library mod to convert Strings to Equation.

"2 - x" --> 2 - x

It autocompletes all the equation and gives you the result. You need to give the values of the variables in the method needed.

Method: StrEq.evaluate("formula", variables, canBeNegative)

variables is Map<String, Double>

You can get it through curseforge and modrinth (under review right now).

If there's something that you didn't understand, ask again. When I can I will do a wiki for this.

**Comment by B4nduty** [comment]
It is now on Modrinth.

**Comment by The-Gmann** [comment]
Thank you for elaborating!
